# ==================================================
# Discord-MC-Chat (DMCC)
# By Xujiayao
#
# Config file for DMCC version & mode:
# Do NOT change these values manually!
version: ${mod_version}
mode: multi_server_client
#
# Discord-MC-Chat Wiki:
# https://dmcc.xujiayao.com/
# ==================================================

# 多服务器功能
multi_server:
  connection:
    host: localhost
    port: 5000
  server_name: SMP
