# ==================================================
# Discord-MC-Chat (DMCC)
# By Xujiayao
#
# Mode file for DMCC version:
# Do NOT change this value manually!
version: ${mod_version}
#
# Discord-MC-Chat Docs:
# https://dmcc.xujiayao.com/
#
# Please choose how this instance of DMCC will operate by setting the "mode" option
# at the bottom of this file to one of the available mode options listed below.
#
# Run "/dmcc reload" command in Minecraft after changing this file.
# A corresponding "config.yml" will be generated.
# After editing "config.yml", run "/dmcc reload" again to apply the changes.
#
# Available mode options:
#
# - single_server:
#     This is the standard, all-in-one mode. This DMCC instance will connect
#     directly to Discord. This is the recommended mode for most users.
#
# - multi_server_client:
#     This is for advanced users running multiple Minecraft servers. In this mode,
#     this DMCC instance will act as a "client". It will not connect to Discord
#     directly. Instead, it will connect to a "standalone" DMCC instance that
#     centralizes all DMCC activities and communicates with Discord.
# ==================================================

# Set your desired mode here.
# Replace "your_option_here" with one of the available modes.
mode: your_option_here
